# This is a sample build configuration for Go.
# This is a sample build configuration for Go.
# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
image: golang:1.7
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - echo $PWD
          - ls
          - export GOPATH=`pwd`  
          - mkdir src
          - mv !(src) src
          - ls
          - echo $PWD
          - mkdir cosmicio
          - mv !(cosmicio) cosmicio
          - go get -v ./...
          - go build -v
          - go test -v
